import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Users, GraduationCap, BookOpen } from 'lucide-react';
var StatisticsRow = function (_a) {
    var enrollmentsCount = _a.enrollmentsCount, teachersCount = _a.teachersCount, coursesCount = _a.coursesCount, isLoadingEnrollments = _a.isLoadingEnrollments, isLoadingStats = _a.isLoadingStats;
    return (_jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8 md:mb-10", children: [_jsx(Card, { children: _jsxs(CardContent, { className: "flex items-center gap-4 p-4", children: [_jsx("div", { className: "p-3 rounded-full bg-blue-100 dark:bg-blue-900/30", children: _jsx(Users, { className: "h-6 w-6 text-blue-600 dark:text-blue-400" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: "\u0625\u062C\u0645\u0627\u0644\u064A \u0627\u0644\u0637\u0644\u0627\u0628" }), isLoadingEnrollments ? (_jsx(Skeleton, { className: "h-7 w-16 mt-1" })) : (_jsx("p", { className: "text-2xl font-bold", children: enrollmentsCount !== null && enrollmentsCount !== void 0 ? enrollmentsCount : '-' }))] })] }) }), _jsx(Card, { children: _jsxs(CardContent, { className: "flex items-center gap-4 p-4", children: [_jsx("div", { className: "p-3 rounded-full bg-purple-100 dark:bg-purple-900/30", children: _jsx(GraduationCap, { className: "h-6 w-6 text-purple-600 dark:text-purple-400" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: "\u0625\u062C\u0645\u0627\u0644\u064A \u0627\u0644\u0645\u0639\u0644\u0645\u064A\u0646" }), isLoadingStats ? (_jsx(Skeleton, { className: "h-7 w-16 mt-1" })) : (_jsx("p", { className: "text-2xl font-bold", children: teachersCount !== null && teachersCount !== void 0 ? teachersCount : '-' }))] })] }) }), _jsx(Card, { children: _jsxs(CardContent, { className: "flex items-center gap-4 p-4", children: [_jsx("div", { className: "p-3 rounded-full bg-emerald-100 dark:bg-emerald-900/30", children: _jsx(BookOpen, { className: "h-6 w-6 text-emerald-600 dark:text-emerald-400" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: "\u0625\u062C\u0645\u0627\u0644\u064A \u0627\u0644\u0645\u0642\u0631\u0631\u0627\u062A" }), isLoadingStats ? (_jsx(Skeleton, { className: "h-7 w-16 mt-1" })) : (_jsx("p", { className: "text-2xl font-bold", children: coursesCount !== null && coursesCount !== void 0 ? coursesCount : '-' }))] })] }) })] }));
};
export default StatisticsRow;
